networks:
  default:
    external:
      name: microservices-network

services:
  postgres_order_db:
    image: postgres:17
    container_name: postgres_order_db
    restart: "no"
    ports:
      - "5433:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: orderroot
      POSTGRES_DB: order_db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  postgres_order_data: